name: "deploy"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - name: "setup deps"
        run: "apk add make bash go mdbook git"
      - name: "clone"
        run: "git clone https://github.com/enckse/voidedtech.com"
      - name: "checkout"
        run: "git -C voidedtech.com checkout $GITHUB_SHA"
      - name: "build dist"
        run: "cd voidedtech.com && make release"
      - name: "archive artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: voidedtech/dist
  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: publish
    steps:
      - name: "download artifacts"
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: "publish"
        uses: cloudflare/pages-action@v1.3.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCT_ID }}
          projectName: voidedtech.com
          directory: dist/
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
