name: "deploy"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v4
      - name: "setup deps"
        run: "apk add make"
      - name: "build dist"
        run: "make"
      - name: "archive artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: publish
    steps:
      - name: "download artifacts"
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: "publish"
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCT_ID }}
          projectName: voidedtech
          directory: dist/
